Begin
DECLARE @LASTNAME AS VARCHAR(10);
DECLARE @FIRSTNAME AS VARCHAR(10);
DECLARE @SECTION AS VARCHAR(10);
DECLARE @SUBJECT AS VARCHAR(20);
DECLARE @DAYTIME AS VARCHAR(30);
DECLARE @ROOM AS VARCHAR(10);
DECLARE @MI AS VARCHAR(10);

SET @LASTNAME = 'PASION';
SET @FIRSTNAME = 'JERVIES';
SET @MI = 'TUZON';
SET @SECTION = 'BSIT 509'; 
SET @SUBJECT = 'ADVANCED DATABASE';
SET @DAYTIME = 'MON 9:00 - 11:00 LEC / TUE 1:00 - 4:00 LAB';
SET @ROOM = '709 / RM309';

PRINT 'NAME: ' + @LASTNAME + ', ' + @FIRSTNAME + ' ' + @LASTNAME + '                                    ' + @SECTION;
PRINT ''
PRINT 'SUBJECT' + @SUBJECT;
PRINT '';
PRINT 'DAY: ' +  @DAYTIME;
PRINT '';
PRINT 'ROOM: ' + @ROOM;
PRINT '';
PRINT 'PRELIM' + '               ' + 'MIDTERM' + '               ' + 'PRE-FINALS' + '               ' +'FINALS';

END